language: d

d:
  - dmd-2.067.0
  - dmd-2.065.0
  - dmd-2.066.1
  - gdc-4.8.2
  - gdc-4.9.0
  - ldc-0.14.0
  - ldc-0.15.1

script:
  - dub test --compiler=$DC || exit 1
  - cd samples/helloworld/
  - dub build --compiler=$DC
